### ISSUE TITLE
Setting up custom template [ziggeorecorder] on WordPress

### ISSUE THREAD

**Issue by korymath** [Ziggeo/ZiggeoWordpressComments#12]
Can I call the shortcode with a template name...? 

[ziggeorecorder template='korycustom'][/ziggeorecorder]

**Comment by Bane-D** [comment]
Hi Kory,

If your template name is `korycustom` then you can call it like so:

`[ziggeo korycustom]`

This will turn it into a recorder for you.

Please try it and let me know how it goes :)

Best,
Bane

**Comment by korymath** [comment]
Thanks for the quick response. 
Getting close: 

```
We cannot recognize your api key. Please make sure to specify it in your website's header.
```

I added my app token to the settings menu here: "Ziggeo API APP Token"

**Comment by korymath** [comment]
Updated the API key and now I am getting: 

```
You are not allowed to access the application from this site.
```

The instructions on setting this up on WP are not immediately clear. Thank you for the help.

**Comment by korymath** [comment]
For reference, the site example is here: https://korymathewson.com/33-diy/

**Comment by Bane-D** [comment]
Hm, I was about to ask you if you added it in the App token field, however seems you already did.

~Without seeing the page, I can only guess that there might be some caching at play, since otherwise it should work.~

* You just added a link :)

So looking at the link I can see token: "6a4...164a" being shown there. The token is considered public, however I always prefer you share it than myself. :)

So that would suggest that you might have some sort of caching on your side (please try CTRL+F5 for hard refresh) and see if the same continues.

I see you modified your post about the error at this point. I am looking at the page and I see that the issue seems to be with the page load of scripts in some way. causing it to show
ReferenceError: ZiggeoApi is not defined
* This suggests that it tries to load this before the ziggeo.js file had a chance to load fully, which should usually not be the case.

We should be able to sort it out by adding this in a wrapper. Will need a moment to test before I can be certain. Will get back to you in a moment.

**Comment by Bane-D** [comment]
Just made the update to the repo here on Github with the change that should help with the same.

Please note that it has many more updates to the plugin compared to Wordpress release (soon to be updated, not just yet).

If you are familiar with FTP please feel free to grab and replace the current plugin files with the files from this repository. If not, we will have the update available soon on Wordpress which will make it easier to upgrade.

In general if you are still getting:
You are not allowed to access the application from this site.

It would basically mean that your token is set to not be used on a domain that it is currently on. Looking at the token now, it is actually not your own app token. This is a session based token that is allowed only to work on our website ;)

Please log into your account and then under Overview menu you will see your own token that you can use.

Regards,
Bane

**Comment by korymath** [comment]
Thank you for the quick fix, incredible support. Thank you. Trying things now and will report. 

ps. I am familiar with WP. Thanks for checking in.

**Comment by korymath** [comment]
Yep. The updated plugin, downloaded as a zip and then uploaded from the wordpress backend worked great!
